---
Name: Catalogue
After: 'framework/*','cms/*'
---
SSViewer:
  theme: 'default'
Catalogue:
  postersAssetsFolderName: '/posters/'
  jsonAssetsFolderName: '/posters/json-metadata/'
GDBackend:
  default_Quality: 80
