---
Name: catalog
After: 'framework/*','cms/*'
---
SSViewer:
  theme: 'default'
Catalog:
  postersAssetsFolderName: '/posters/'
  jsonAssetsFolderName: '/posters/json-metadata/'
  apiKey: 'a0f02af4'
GDBackend:
  default_Quality: 80
