---
Name: Catalogue
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'app'
    - '$default'

# Adds a new title field that we can query GraphQL with.
SilverStripe\Assets\File:
  db:
    FolderTitle: 'Varchar(255)'
